# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install de421"
  - "pip install unittest2"
  - "pip install ./jplephem/"
  - "wget http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de421.bsp"

script:
  - "unit2 jplephem.test"
