# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# The old version of NumPy installed here is in support of users who
# cannot upgrade relentlessly.
# https://github.com/brandon-rhodes/python-jplephem/issues/35

install:
  - "pip install numpy==1.11.3 unittest2"
  - "python setup.py sdist"
  - "mv jplephem trash"
  - "pip install dist/jplephem-*.tar.gz"

script:
  - "cd ci"
  - "unit2 jplephem.test"
  - "python -m jplephem.jpltest"
