# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install unittest2"
  - "python setup.py sdist"
  - "mv jplephem trash"
  - "pip install dist/jplephem-*.tar.gz"

script:
  - "cd ci && unit2 jplephem.test"
  - "cd ci && python -m jplephem.jpltest"
