# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - "pip install unittest2"
  - "python setup.py sdist"
  - "mv jplephem trash"
  - "pip install dist/jplephem-*.tar.gz"
  - "wget http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de405.bsp"
  - "wget http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de421.bsp"
  - "wget http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp"
  - "wget ftp://ssd.jpl.nasa.gov/pub/eph/planets/test-data/430/testpo.430"

script:
  - "unit2 jplephem.test"
  - "python -m jplephem.jpltest"
