package:
  name: jplephem
  version: "2.1"

source:
  fn: jplephem-2.1.tar.gz
  url: https://pypi.python.org/packages/source/j/jplephem/jplephem-2.1.tar.gz
  md5: d20989d5ea2fea493805a9d11ec02aae

build:
  number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - jplephem

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT License
  summary: 'Python version of NASA DE4xx ephemerides, the basis for the 
Astronomical Alamanac'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
